services:
    app.repository.entry:
        class: AppBundle\Repository\EntryRepository
        factory: ["@doctrine", getRepository]
        arguments: [AppBundle\Entity\Entry ]
    app.repository.comment:
        class: AppBundle\Repository\CommentRepository
        factory: ["@doctrine", getRepository]
        arguments: [AppBundle\Entity\Comment ]
    app.repository.author:
        class: AppBundle\Repository\AuthorRepository
        factory: ["@doctrine", getRepository]
        arguments: [AppBundle\Entity\Author ]
    app.paginator_aware:
        class: AppBundle\Repository\PaginatorAwareRepository
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }