#parameters:
#    parameter:
#        key: 'appbundle.paginator_aware.class'


services:
    app.repository.entry:
        class: AppBundle\Repository\EntryRepository
        factory: ["@doctrine", getRepository]
        arguments: [AppBundle\Entity\Entry ]
#    app.paginator_aware