<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Entry;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAll()
    {
        return $this->createQueryBuilder("e");
    }	
	
    /**
     * @param $query
     * @return \Doctrine\ORM\Query
     */
	public function findEntriesByQuery($query)
	{
	    $qb = $this->createQueryBuilder('e')
            ->where('e.content LIKE :query')
            ->orderBy('e.updatedAt', 'DESC')
            ->setParameter('term', "%$query%")
        ;

        return $qb->getQuery();
	}

    /**
     * @return \Doctrine\ORM\Query
     */
	public function getLatestEntries()
	{
        $qb = $this->createQueryBuilder('e')
            ->orderBy('e.updatedAt', 'DESC');

        return $qb->getQuery();
	}

    /**
     * @return Entry|null
     */
	public function findMostRecent()
    {
        $qb = $this->createQueryBuilder('e')
            ->orderBy('e.updatedAt', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
